---

- name: Get CRI-O apt-key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/Release.key
    state: present

- name: Get CRI-O apt-key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27:/1.27.0/Debian_11/Release.key
    state: present

- name: Add CRI-O stable repo
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/ /
    state: present
    filename: cri-o-stable

- name: Add CRI-O stable repo
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27/Debian_11/ /
    state: present
    filename: cri-o-1.27

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - cri-o
      - cri-tools
      - cri-o-runc

- name: Reload configs
  systemd: daemon_reload=yes

- name: Enable CRI-O Service
  systemd:
    name: crio
    enabled: yes

- name: Starting CRI-O is running
  systemd:
    state: started
    name: crio
