---

- name: Add Kubernetes apt repository key.
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key"
    dest: /etc/apt/keyrings/cri-o-apt-keyring.gpg
    mode: '0644'
    force: true

- name: Add Kubernetes apt repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /"
    state: present
    update_cache: yes

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - cri-o
      - cri-tools

- name: Reload configs
  systemd: daemon_reload=yes

- name: Remove 100-crio-bridge.conflist
  file:
    path: "/etc/cni/net.d/100-crio-bridge.conflist"
    state: "absent"

- name: Remove 200-loopback.conflist
  file:
    path: "/etc/cni/net.d/200-loopback.conflist"
    state: "absent"

- name: Enable CRI-O Service
  systemd:
    name: crio
    enabled: yes

- name: Start CRI-O
  systemd:
    state: started
    name: crio
